name: 'Setup DuckDB'
description: 'Downloads and installs DuckDB with caching'

inputs:
  version:
    description: 'DuckDB version to install'
    required: true
  arch:
    description: 'Architecture to install (amd64 or aarch64)'
    required: true

runs:
  using: "composite"
  steps:
    - name: DuckDB package cache
      id: duckdb-cache
      uses: actions/cache@v4
      with:
        path: libduckdb-linux-${{ inputs.arch }}.zip
        key: ${{ runner.os }}-duckdb-${{ inputs.arch }}-v${{ inputs.version }}

    - name: Download DuckDB
      if: steps.duckdb-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        wget https://github.com/duckdb/duckdb/releases/download/v${{ inputs.version }}/libduckdb-linux-${{ inputs.arch }}.zip

    - name: Install DuckDB
      shell: bash
      run: |
        set -ex
        unzip -o libduckdb-linux-${{ inputs.arch }}.zip -d libduckdb
        sudo mv libduckdb/duckdb.* /usr/local/include/
        sudo mv libduckdb/libduckdb.so /usr/local/lib
        sudo ldconfig /usr/local/lib
